services:
  ai-mobile-api:
    build: .
    container_name: projek-anakmagang-ai-mobile-api
    command: python mobile_api.py
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env

  ai-recognition-worker:
    build: .
    container_name: projek-anakmagang-ai-recognition-worker
    command: python recognition.py
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
