services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554" # RTSP
      - "1935:1935" # RTMP
      - "8888:8888" # HLS
      - "8889:8889" # WebRTC HTTP
      - "8189:8189/udp" # WebRTC ICE UDP
      - "8189:8189/tcp" # WebRTC ICE TCP
    environment:
      - MTX_PROTOCOLS=tcp
      - MTX_WEBRTCADDITIONALHOSTS=192.168.99.56
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis_middleware
    ports:
      - "6379:6379"
    restart: unless-stopped
