version: '3.8'
services:
  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: mediamtx
    ports:
      - "8554:8554" # RTSP
      - "1935:1935" # RTMP
      - "8888:8888" # HLS
      - "8889:8889" # WebRTC
    environment:
      - MTX_PROTOCOLS=tcp
    restart: unless-stopped

  redis:
    image: redis:alpine
    container_name: redis_middleware
    ports:
      - "6379:6379"
    restart: unless-stopped

  ml_core:
    build: .
    container_name: ml_core_cpp
    depends_on:
      - redis
      - mediamtx
    env_file:
      - .env
    environment:
      - REDIS_URL=tcp://redis:6379
      - REDIS_CHANNEL=face_preprocessed_queue
      - CAMERA_ID=cam_01
    restart: unless-stopped
